Remove jQuery from frontend scripts
CTMobi/rate-my-post pull request #1
Opened 2022-11-18 13:32 UTC by alfredoct96

This PR remove jQuery from frontend scripts.

JQuery reduces site performance, and not all sites use jQuery and could therefore have problems installing Rate My Post.

For this reason with this pull request convert all the jQuery features used in the frontend code into classic Javascript, so as to give all sites the possibility to install the plugin.

I committed also the .pot file, is the correct way? And i didn't edit the rate-my-post.js inside public dir, i didn't find a command for build it.

2022-11-18 14:02 UTC, alessandrocarrera approved these changes

2022-11-18 14:27 UTC, HyprCoder requested changes

2022-11-18 14:27 UTC, HyprCoder commented on _dev/public/js/modules/CookieCheck.js
> +    if(postsArray.indexOf(this.postID) === -1) {
The includes() function may be more appropriate. Check if it works.

2022-11-21 13:37 UTC, HyprCoder approved these changes

2022-11-21 13:37 UTC, merged